<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>SpecializedStorage</AssemblyName>
    <RootNamespace>SpecializedStorage</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="resources\stack-marker.pixels">
      <LogicalName>SpecializedStorage.Resources.StackMarker.pixels</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="references\Assembly-CSharp-firstpass\Assembly-CSharp-firstpass.csproj" Private="false" />
    <ProjectReference Include="references\Assembly-CSharp\Assembly-CSharp.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.BaseLib" Version="5.4.21" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.9.0" />
    <PackageReference Include="Unity3D.SDK" Version="2020.3.13.1" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
